name: Publish docs

on:
  push:
    branches:
      - main
    paths:
      - "apps/docs/**"

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_DOCS_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DOCS_PROJECT_ID }}

jobs:
  deploy-docs-to-vercel:
    name: Deploy docs to vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v5

      - name: Setup bun environment
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install depenendecies
        run: bun install

      - name: Install vercel cli
        run: bun add --global vercel@latest

      - name: Pull vercel environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build project artifacts
        run: NITRO_PRESET=vercel vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy project artifacts to vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
